### PR TITLE
Add status of open to a new task

### PR DESCRIPTION
**Pull request by ceca2017**
### Add status of open to a new task
https://www.pivotaltracker.com/story/show/147344743

* Set status field to 'open' when new task created

### CODE REVIEW

**Review by mmollerstrom — COMMENTED** [review]
This is just a hardcoded “open task”, I don’t see anything in the views, with like a drop down list or anything like that, am I missing something that was done or talked about?

**Comment by benjamincomley** [comment]
That's all it needs to be. When a new bid is created, the system sets it's status to "Open". It will stay in this state until the first bid is made, at which point the system will change it's status to "Bidding". 

There is nothing manual to do here, and displaying the status in a view was not part of the task.

**Comment by mmollerstrom** [comment]
My bad Benji! But you need to merge the develop, into post new tasks and push to origin again to make it pass

**Comment by benjamincomley** [comment]
This ones on Claes' computer so we'll have to leave it till he gets up tomorrow.

**Pull request merged**
